name: Build Tweak
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Randomblock1/theos-action@v1
        with:
          theos_sdks: https://github.com/theos/sdks
      - uses: actions/upload-artifact@v3
        with:
          name: FixAudioTikTok
          path: packages/*.deb
