Package: com.minhtan.fixaudiotiktok
Name: FixAudioTikTok
Depends: mobilesubstrate
Version: 0.0.1
Architecture: iphoneos-arm64
Description: Fix audio for VCam on TikTok
Maintainer: minhtan
Author: minhtan
Section: Tweaks
